services:
  db:
    container_name: db
    image: ghcr.io/baosystems/postgis:17-3.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: postgres -c shared_buffers=2GB -c maintenance_work_mem=2GB -c max_wal_size=8GB
    shm_size: 1gb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    container_name: app
    build: .
    restart: unless-stopped
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./tmp:/app/tmp
      - ./rnb_to_osm/data:/app/rnb_to_osm/data/

  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    labels:
      - com.github.nginx-proxy.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    restart: unless-stopped
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
    depends_on:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  postgres_data:
  certs:
  html:
  acme:
