version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    ports:
      - "5000:5000"
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./tmp:/app/tmp

volumes:
  postgres_data:
