[project]
name = "rnb-osm-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "flask-sqlalchemy>=3.1.1",
    "geoalchemy2>=0.17.1",
    "overpy>=0.7",
    "psycopg2-binary>=2.9.10",
    "requests>=2.32.4",
    "sentry-sdk>=2.30.0",
    "shapely>=2.1.1",
]
